@startuml
class model.ItensPedido {
- int IdItem
- int Numpedido
- int IdProduto
- double quantidade
+ <<Create>> ItensPedido()
+ <<Create>> ItensPedido(int,int,int,double)
+ int getIdItem()
+ void setIdItem(int)
+ int getNumpedido()
+ void setNumpedido(int)
+ int getIdProduto()
+ void setIdProduto(int)
+ double getQuantidade()
+ void setQuantidade(double)
+ String toString()
}
class model.Pedido {
- int NumPedido
- int IdCLiente
- String dataPedido
- String dataViagem
+ <<Create>> Pedido()
+ <<Create>> Pedido(int,int,String,String)
+ int getNumPedido()
+ void setNumPedido(int)
+ int getIdCLiente()
+ void setIdCLiente(int)
+ String getDataPedido()
+ void setDataPedido(String)
+ String getDataViagem()
+ void setDataViagem(String)
+ String toString()
}
class model.Cliente {
- int id
- String nomeCliente
- String cpf
- String logadouro
- String cidade
- String uf
- String cep
- String telefoneCelular
- String dataCadastro
+ <<Create>> Cliente()
+ <<Create>> Cliente(int,String,String,String,String,String,String,String,String)
+ int getId()
+ void setId(int)
+ String getNomeCliente()
+ void setNomeCliente(String)
+ String getCpf()
+ void setCpf(String)
+ String getLogadouro()
+ void setLogadouro(String)
+ String getCidade()
+ void setCidade(String)
+ String getUf()
+ void setUf(String)
+ String getCep()
+ void setCep(String)
+ String getTelefoneCelular()
+ void setTelefoneCelular(String)
+ String getDataCadastro()
+ void setDataCadastro(String)
+ String toString()
}
class model.Produto {
- int IdProduto
- String Descricao
- double ValorUnit
+ <<Create>> Produto()
+ <<Create>> Produto(int,String,double)
+ int getIdProduto()
+ void setIdProduto(int)
+ String getDescricao()
+ void setDescricao(String)
+ double getValorUnit()
+ void setValorUnit(double)
+ String toString()
}
@enduml